const ProdutosExemplo = [
    {
        codigo: "1234",
        marca: "Danin",
        modelo: "Vestigo Longo",
        preco: 600,
        descricao: "Vestido longo verde sem mangas",
        imagem: "https://2thedress.com.br/thumbs/lookbook-06-24//3P3A4528.w_600.h_600.jpg",
        promocao: false,
    },
    {
        codigo: "1235",
        marca: "MinimalWear",
        modelo: "Básica",
        preco: 69.90,
        descricao: "Blusa de algodão com corte reto e gola redonda, ideal para o dia a dia. Disponível nas cores preta, branca e azul.",
        imagem: "https://hering.vtexassets.com/arquivos/ids/864873-800-auto/02TQ-HN1EN-C1.jpg?v=638495486548630000",
        promocao: true,
    },
    {
        codigo: "1236",
        marca: "UrbanStyle",
        modelo: "Jaqueta Clássica",
        preco: 300,
        descricao: "Jaqueta jeans clássica com bolsos frontais e fechamento por botões. Perfeita para looks casuais.",
        imagem: "https://hering.vtexassets.com/arquivos/ids/1797752-800-auto/H8BX-1ASN-C1.jpg?v=638642637989630000",
        promocao: true,
    },
    {
        codigo: "1237",
        marca: "SummerChic",
        modelo: "Midi Floral",
        preco: 200,
        descricao: "Vestido midi com estampa floral, decote em V e ajuste na cintura. Ideal para ocasiões mais descontraídas.",
        imagem: "https://hering.vtexassets.com/arquivos/ids/855113-800-auto/K5CX-N10SI-C1.jpg?v=638495243137700000",
        promocao: true,
    },
    {
        codigo: "1238",
        marca: "FashionFit",
        modelo: "Skinny",
        preco: 359.59,
        descricao: "Calça skinny de tecido confortável com cintura alta. Disponível em cores neutras.",
        imagem: "https://hering.vtexassets.com/arquivos/ids/1668588-800-auto/H9J3-1BSN-C2.jpg?v=638617726370470000",
        promocao: false,
    },
    {
        codigo: "1239",
        marca: "CasualWear",
        modelo: "Listrada",
        preco: 600,
        descricao: "Camiseta de algodão com listras horizontais. Estilo casual e moderno, ideal para o dia a dia.",
        imagem: "https://hering.vtexassets.com/arquivos/ids/859450-800-auto/4K2T-1HEN-C1.jpg?v=638495376548570000",
        promocao: false,
    },
    {
        codigo: "1240",
        marca: "ClassyLook",
        modelo: "Longo",
        preco: 279.99,
        descricao: "Macacão de tecido leve com decote redondo e calça reta. Perfeito para eventos sociais.",
        imagem: "https://hering.vtexassets.com/arquivos/ids/1955537-800-auto/K5TZ-N10SI-C1.jpg?v=638658190742030000",
        promocao: false,
    },
    {
        codigo: "1241",
        marca: "FormalMen",
        modelo: "Social",
        preco: 139.90,
        descricao: "Camisa social branca de algodão com corte slim fit. Básica e indispensável no guarda-roupa.",
        imagem: "https://img.lojasrenner.com.br/item/916264938/original/12.jpg",
        promocao: false,
    },
    {
        codigo: "1242",
        marca: "DenimDream",
        modelo: "Curta",
        preco: 119.90,
        descricao: "Saia jeans com corte acima do joelho e barra desfiada. Despojada e moderna para diversas ocasiões.",
        imagem: "https://img.lojasrenner.com.br/item/928166796/original/4.jpg",
        promocao: false,
    }
]
export default ProdutosExemplo